"use client";

import { useMemo, useState } from "react";

type University = { id:number; name:string; short:string; city:string; country:string; flag:string; rank:number; acceptance:number; international:number; tuition:string; tuitionValue:number; exams:string[]; deadline:string; type:string; accent:string };
const universities: University[] = [
  {id:1,name:"University of Toronto",short:"U of T",city:"Торонто",country:"Канада",flag:"🇨🇦",rank:21,acceptance:43,international:28,tuition:"$45–62 тыс.",tuitionValue:53,exams:["IELTS 6.5","GPA 3.7+","SAT optional"],deadline:"15 января",type:"Государственный",accent:"#244e8e"},
  {id:2,name:"University of Amsterdam",short:"UvA",city:"Амстердам",country:"Нидерланды",flag:"🇳🇱",rank:55,acceptance:51,international:36,tuition:"€12–18 тыс.",tuitionValue:15,exams:["IELTS 6.5","Аттестат 4.5+","Мотивационное письмо"],deadline:"1 апреля",type:"Государственный",accent:"#b82c38"},
  {id:3,name:"Technical University of Munich",short:"TUM",city:"Мюнхен",country:"Германия",flag:"🇩🇪",rank:30,acceptance:33,international:41,tuition:"€4–6 тыс.",tuitionValue:5,exams:["IELTS 6.5","TestAS","GPA 3.5+"],deadline:"15 июля",type:"Государственный",accent:"#3777a8"},
  {id:4,name:"University of Melbourne",short:"UniMelb",city:"Мельбурн",country:"Австралия",flag:"🇦🇺",rank:14,acceptance:70,international:44,tuition:"$32–48 тыс.",tuitionValue:40,exams:["IELTS 6.5","GPA 3.3+","Foundation year"],deadline:"31 октября",type:"Государственный",accent:"#082f56"},
  {id:5,name:"Bocconi University",short:"Bocconi",city:"Милан",country:"Италия",flag:"🇮🇹",rank:52,acceptance:38,international:24,tuition:"€16–18 тыс.",tuitionValue:17,exams:["IELTS 6.5","SAT 1350+","Bocconi Test"],deadline:"12 апреля",type:"Частный",accent:"#a33c54"},
  {id:6,name:"Nazarbayev University",short:"NU",city:"Астана",country:"Казахстан",flag:"🇰🇿",rank:501,acceptance:57,international:12,tuition:"$15 тыс.",tuitionValue:15,exams:["IELTS 6.0","NUET / SAT","GPA 4.0+ из 5"],deadline:"28 февраля",type:"Автономный",accent:"#15776c"},
  {id:7,name:"University College London",short:"UCL",city:"Лондон",country:"Великобритания",flag:"🇬🇧",rank:9,acceptance:24,international:48,tuition:"£28–39 тыс.",tuitionValue:42,exams:["IELTS 7.0","A-level AAA","Personal Statement"],deadline:"29 января",type:"Государственный",accent:"#5f4a8b"},
  {id:8,name:"New York University",short:"NYU",city:"Нью-Йорк",country:"США",flag:"🇺🇸",rank:43,acceptance:13,international:26,tuition:"$58–63 тыс.",tuitionValue:61,exams:["TOEFL 100+","GPA 3.7+","SAT optional"],deadline:"5 января",type:"Частный",accent:"#6b2c91"},
  {id:9,name:"Sorbonne University",short:"SU",city:"Париж",country:"Франция",flag:"🇫🇷",rank:63,acceptance:35,international:21,tuition:"€3–12 тыс.",tuitionValue:8,exams:["Французский B2","Аттестат 4.5+","Campus France"],deadline:"15 марта",type:"Государственный",accent:"#243f86"},
  {id:10,name:"National University of Singapore",short:"NUS",city:"Сингапур",country:"Сингапур",flag:"🇸🇬",rank:8,acceptance:10,international:27,tuition:"$18–32 тыс.",tuitionValue:25,exams:["IELTS 6.5","SAT 1450+","GPA 3.8+"],deadline:"26 февраля",type:"Государственный",accent:"#ef7c00"},
  {id:11,name:"KAIST",short:"KAIST",city:"Тэджон",country:"Южная Корея",flag:"🇰🇷",rank:56,acceptance:20,international:12,tuition:"$6–8 тыс.",tuitionValue:7,exams:["IELTS 6.5","SAT / ACT","Recommendation"],deadline:"7 января",type:"Государственный",accent:"#164788"},
  {id:12,name:"Aalto University",short:"Aalto",city:"Эспоо",country:"Финляндия",flag:"🇫🇮",rank:109,acceptance:17,international:24,tuition:"€12–15 тыс.",tuitionValue:14,exams:["IELTS 6.5","SAT 1300+","Portfolio optional"],deadline:"22 января",type:"Государственный",accent:"#da3b45"},
  {id:13,name:"University of Barcelona",short:"UB",city:"Барселона",country:"Испания",flag:"🇪🇸",rank:165,acceptance:62,international:18,tuition:"€4–7 тыс.",tuitionValue:6,exams:["Испанский B2","UNEDasiss","Аттестат"],deadline:"30 июня",type:"Государственный",accent:"#8e1839"},
  {id:14,name:"ETH Zurich",short:"ETH",city:"Цюрих",country:"Швейцария",flag:"🇨🇭",rank:7,acceptance:27,international:41,tuition:"CHF 3 тыс.",tuitionValue:3,exams:["IELTS 7.0","Немецкий C1","Вступительный экзамен"],deadline:"31 марта",type:"Государственный",accent:"#4b708b"},
  {id:15,name:"University of Tokyo",short:"UTokyo",city:"Токио",country:"Япония",flag:"🇯🇵",rank:28,acceptance:34,international:15,tuition:"$4–6 тыс.",tuitionValue:5,exams:["IELTS 6.5","EJU / SAT","Мотивационное эссе"],deadline:"13 декабря",type:"Государственный",accent:"#243c78"},
  {id:16,name:"Middle East Technical University",short:"METU",city:"Анкара",country:"Турция",flag:"🇹🇷",rank:285,acceptance:42,international:9,tuition:"$3–8 тыс.",tuitionValue:6,exams:["IELTS 6.5","SAT 1200+","Аттестат"],deadline:"12 июля",type:"Государственный",accent:"#b62634"},
  {id:17,name:"Khalifa University",short:"KU",city:"Абу-Даби",country:"ОАЭ",flag:"🇦🇪",rank:202,acceptance:35,international:28,tuition:"$22–27 тыс.",tuitionValue:25,exams:["IELTS 6.0","SAT Math 700+","GPA 3.0+"],deadline:"2 июня",type:"Государственный",accent:"#2e7b75"},
  {id:18,name:"Tsinghua University",short:"THU",city:"Пекин",country:"Китай",flag:"🇨🇳",rank:20,acceptance:12,international:8,tuition:"$4–6 тыс.",tuitionValue:5,exams:["IELTS 6.5","HSK 5","GPA 3.7+"],deadline:"28 февраля",type:"Государственный",accent:"#76539a"}
];
const countries=["Все страны",...Array.from(new Set(universities.map(u=>u.country)))];

export default function Home(){
 const [query,setQuery]=useState(""); const [country,setCountry]=useState("Все страны"); const [budget,setBudget]=useState(65); const [saved,setSaved]=useState<number[]>([]); const [compare,setCompare]=useState<number[]>([]); const [showFilters,setShowFilters]=useState(false);
 const filtered=useMemo(()=>universities.filter(u=>(country==="Все страны"||u.country===country)&&u.tuitionValue<=budget&&`${u.name} ${u.city} ${u.country}`.toLowerCase().includes(query.toLowerCase())),[query,country,budget]);
 const toggleCompare=(id:number)=>setCompare(old=>old.includes(id)?old.filter(x=>x!==id):old.length<3?[...old,id]:old);
 return <main>
  <header className="nav"><a className="brand" href="#top"><span className="brandmark">U</span>UniGuide</a><nav><a href="#catalog">Университеты</a><a href="#how">Как поступить</a><a href="#guide">Гайды</a></nav><div className="nav-actions"><button className="saved-btn">♡ <span>Избранное</span><b>{saved.length}</b></button><button className="primary small" onClick={()=>document.querySelector("#catalog")?.scrollIntoView({behavior:"smooth"})}>Найти вуз</button></div></header>
  <section className="hero" id="top"><div className="hero-copy"><div className="eyebrow">◌ База из 1 200+ университетов</div><h1>Найди университет,<br/><em>который подходит тебе</em></h1><p>Требования, стоимость, статистика поступления и честное сравнение — всё в одном месте.</p><div className="searchbox"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Университет, город или страна" aria-label="Поиск университета"/><button onClick={()=>document.querySelector("#catalog")?.scrollIntoView({behavior:"smooth"})}>Искать</button></div><div className="quick"><span>Популярное:</span>{["Канада","Германия","Нидерланды"].map(c=><button key={c} onClick={()=>{setCountry(c);document.querySelector("#catalog")?.scrollIntoView({behavior:"smooth"})}}>{c}</button>)}</div></div>
  <div className="hero-visual"><div className="orb orb1"/><div className="orb orb2"/><div className="campus-card"><div className="mini-top"><span>🇳🇱</span><b>University of Amsterdam</b><i>♡</i></div><div className="campus-image"><div className="sun"/><div className="building"><span/><span/><span/><span/><span/></div></div><div className="mini-stats"><span><b>51%</b>поступают</span><span><b>36%</b>иностранцев</span><span><b>#55</b>в мире</span></div></div><div className="float-card fc1"><b>✓</b><span>Шансы поступить<strong>Высокие</strong></span></div><div className="float-card fc2"><b>12</b><span>вузов<br/>в вашем списке</span></div></div></section>
  <section className="trust"><span>Данные собраны из открытых источников и официальных сайтов вузов</span><div><b>1 200+</b> университетов</div><div><b>38</b> стран</div><div><b>2026</b> актуальные данные</div></section>
  <section className="catalog" id="catalog"><div className="section-head"><div><span className="section-kicker">Каталог университетов</span><h2>Сравнивай. Выбирай. Поступай.</h2><p>Настрой фильтры — мы покажем вузы, подходящие под твои цели.</p></div><button className="filter-toggle" onClick={()=>setShowFilters(!showFilters)}>☷ Фильтры</button></div>
  <div className={`filters ${showFilters?"open":""}`}><label>Страна<select value={country} onChange={e=>setCountry(e.target.value)}>{countries.map(c=><option key={c}>{c}</option>)}</select></label><label>Бюджет в год <strong>до ${budget} тыс.</strong><input type="range" min="5" max="65" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><label>Направление<select><option>Любое направление</option><option>Бизнес и экономика</option><option>IT и инженерия</option><option>Медицина</option></select></label><label>Уровень<select><option>Бакалавриат</option><option>Магистратура</option><option>PhD</option></select></label></div>
  <div className="results-line"><b>Найдено: {filtered.length} университетов</b><span>Сортировка: <select><option>По соответствию</option><option>По рейтингу</option><option>По стоимости</option></select></span></div><div className="cards">{filtered.map(u=><article className="uni-card" key={u.id} style={{"--accent":u.accent} as React.CSSProperties}><div className="card-top"><div className="uni-logo">{u.short.slice(0,2)}</div><div><div className="uni-meta">{u.flag} {u.city}, {u.country} · {u.type}</div><h3>{u.name}</h3></div><button className={`heart ${saved.includes(u.id)?"active":""}`} onClick={()=>setSaved(s=>s.includes(u.id)?s.filter(x=>x!==u.id):[...s,u.id])}>{saved.includes(u.id)?"♥":"♡"}</button></div><div className="metrics"><div><span>Мировой рейтинг</span><b>#{u.rank}</b></div><div><span>Средний приём</span><b>{u.acceptance}%</b></div><div><span>Иностранцы</span><b>{u.international}%</b></div><div><span>Стоимость / год</span><b>{u.tuition}</b></div></div><div className="requirements"><span>Требования</span><div>{u.exams.map(e=><em key={e}>{e}</em>)}</div></div><div className="card-foot"><span>◷ Дедлайн: <b>{u.deadline}</b></span><button className={compare.includes(u.id)?"compared":""} onClick={()=>toggleCompare(u.id)}>{compare.includes(u.id)?"✓ В сравнении":"＋ Сравнить"}</button><button className="details">Подробнее →</button></div></article>)}</div>{!filtered.length&&<div className="empty"><b>Ничего не найдено</b><p>Попробуйте увеличить бюджет или выбрать другую страну.</p></div>}</section>
  <section className="how" id="how"><span className="section-kicker">Путь к поступлению</span><h2>От мечты до оффера — по шагам</h2><div className="steps">{[["01","Определи цель","Страна, специальность и бюджет"],["02","Собери список","Сравни требования и шансы"],["03","Подготовь документы","Экзамены, эссе и рекомендации"],["04","Отправь заявку","Следи за сроками в одном месте"]].map(([n,t,d])=><div key={n}><i>{n}</i><b>{t}</b><span>{d}</span></div>)}</div></section>
  <section className="cta" id="guide"><div><span>Твой следующий шаг</span><h2>Не знаешь, с чего начать?</h2><p>Ответь на 7 вопросов — и получи персональную подборку университетов.</p></div><button className="primary">Подобрать университеты →</button></section>
  <footer><a className="brand" href="#top"><span className="brandmark">U</span>UniGuide</a><p>Твой навигатор в мире высшего образования.</p><span>© 2026 UniGuide · Данные носят справочный характер</span></footer>
  {compare.length>0&&<div className="compare-bar"><span><b>{compare.length}</b> выбрано для сравнения</span><div>{compare.map(id=><i key={id}>{universities.find(u=>u.id===id)?.short}</i>)}</div><button onClick={()=>setCompare([])}>Очистить</button><button className="primary small">Сравнить →</button></div>}
 </main>
}
