@extends('layouts.app')
@section('title','UniGuide — найди свой университет')
@section('content')
<header class="nav"><a class="brand" href="/"><span>U</span>UniGuide</a><nav><a href="#catalog">Университеты</a><a href="#how">Как поступить</a><a href="{{ route('login') }}">Админ-панель</a></nav><a class="btn" href="#catalog">Найти вуз</a></header>
<section class="hero"><div><div class="eyebrow">◌ База университетов мира</div><h1>Найди университет,<br><em>который подходит тебе</em></h1><p>Требования, стоимость, статистика поступления и честное сравнение — всё в одном месте.</p><div class="search"><span>⌕</span><input id="search" placeholder="Университет, город или страна"><button onclick="document.querySelector('#catalog').scrollIntoView({behavior:'smooth'})">Искать</button></div></div><div class="hero-card"><div class="orbit"></div><article><small>🇳🇱 Амстердам, Нидерланды</small><h3>University of Amsterdam</h3><div class="campus"><i></i><b></b></div><div class="mini"><span><strong>51%</strong>поступают</span><span><strong>36%</strong>иностранцев</span><span><strong>#55</strong>в мире</span></div></article><aside>✓ <span>Шансы поступить<b>Высокие</b></span></aside></div></section>
<section class="trust"><span>Данные из открытых источников и официальных сайтов вузов</span><div><b>{{ $universities->count() }}</b> университетов</div><div><b>{{ $countries->count() }}</b> стран</div><div><b>2026</b> актуальные данные</div></section>
<main class="catalog" id="catalog"><div class="section-head"><div><span>КАТАЛОГ УНИВЕРСИТЕТОВ</span><h2>Сравнивай. Выбирай. Поступай.</h2><p>Настрой фильтры — мы покажем вузы, подходящие под твои цели.</p></div></div>
<div class="filters"><label>Страна<select id="country"><option value="">Все страны</option>@foreach($countries as $country)<option>{{ $country }}</option>@endforeach</select></label><label>Бюджет в год <strong id="budgetLabel">до $65 тыс.</strong><input id="budget" type="range" min="3" max="65" value="65"></label><label>Минимальный приём<select id="acceptance"><option value="0">Любой процент</option><option value="20">От 20%</option><option value="40">От 40%</option><option value="60">От 60%</option></select></label></div>
<div class="result-line"><b>Найдено: <span id="count">{{ $universities->count() }}</span></b></div>
<div class="cards" id="cards">@foreach($universities as $university)<article class="uni-card" data-search="{{ mb_strtolower($university->name.' '.$university->city.' '.$university->country) }}" data-country="{{ $university->country }}" data-budget="{{ $university->tuition_value }}" data-acceptance="{{ $university->acceptance_rate }}" style="--accent:{{ $university->accent }}"><div class="card-top"><div class="logo">{{ mb_substr($university->short_name,0,3) }}</div><div><small>{{ $university->flag }} {{ $university->city }}, {{ $university->country }} · {{ $university->type }}</small><h3>{{ $university->name }}</h3></div><button class="heart">♡</button></div><div class="metrics"><div><span>Мировой рейтинг</span><b>#{{ $university->world_rank }}</b></div><div><span>Средний приём</span><b>{{ $university->acceptance_rate }}%</b></div><div><span>Иностранцы</span><b>{{ $university->international_rate }}%</b></div><div><span>Стоимость / год</span><b>{{ $university->tuition }}</b></div></div><div class="req"><span>Требования</span><p>@foreach($university->requirements as $requirement)<em>{{ $requirement }}</em>@endforeach</p></div><footer><span>◷ Дедлайн: <b>{{ $university->deadline }}</b></span><button>＋ Сравнить</button><button class="dark">Подробнее →</button></footer></article>@endforeach</div><div class="empty" id="empty" hidden>Ничего не найдено. Измените параметры поиска.</div></main>
<section class="how" id="how"><span>ПУТЬ К ПОСТУПЛЕНИЮ</span><h2>От мечты до оффера — по шагам</h2><div>@foreach([['01','Определи цель','Страна, специальность и бюджет'],['02','Собери список','Сравни требования и шансы'],['03','Подготовь документы','Экзамены, эссе и рекомендации'],['04','Отправь заявку','Следи за сроками в одном месте']] as $step)<article><i>{{ $step[0] }}</i><b>{{ $step[1] }}</b><small>{{ $step[2] }}</small></article>@endforeach</div></section>
<footer class="site-footer"><a class="brand" href="/"><span>U</span>UniGuide</a><p>Твой навигатор в мире высшего образования.</p><small>© 2026 UniGuide · Данные носят справочный характер</small></footer>
@endsection
